### ISSUE TITLE
calculate snapsize

### ISSUE THREAD

**Issue by Paradroid** [marxarelli/amlvm-snapshot#1]
The calculate_snapsize function calculates using the number of free extents, but the --size option for lvcreate seems to want a size in bytes (or m or g)
I think if you do something like 

<pre>
my $extent_size = $parts[12];
my $free_extents  = $parts[15];
...
$self->{snapsize} = $extent_size * $free_extents . "k"
#append k because default is megabytes
</pre>

Also when I set 
property "SNAPSHOT-SIZE" "1000"
in my dumptype it doesnt seem to affect the size of the actual snapshot

I've currently got the value hardcoded in the lvcreate line.

**Comment by Paradroid** [comment]
or you could keep your code the same and just use --extents in the lvcreate command instead of --size :)

**Comment by Paradroid** [comment]
Damn I didnt mean to close this... oh well :)

**Comment by marxarelli** [comment]
Thanks for catching this. I'll modify the invocation of `lvcreate` to use `--extents`.

**Comment by marxarelli** [comment]
Fixed lvcreate execution.

Modified invocation of `lvcreate` to use `--extents` option, which takes
the snapshot size in extents as the argument, instead of `--size`.

closed by 17bcf96e3a17683420a263f569c54d3165ad7b36
