### ISSUE TITLE
Amanda::Script_App::print_to_server_and_die() has changed its arguments.

### ISSUE THREAD

**Issue by zimage** [marxarelli/amlvm-snapshot#2]
The 'action' argument has been removed from recent versions of print_to_server_and_die().  Your script can be fixed by removing the first empty-string argument to print_to_server_and_die().

**Comment by marxarelli** [comment]
Hmm. Do you know the version in which the argument was removed? Maybe I should create a branch for it to maintain compatibility with past versions (like the one I use).

**Comment by zimage** [comment]
I don't know what version, but the commit was about a year ago.
http://github.com/zmanda/amanda/commit/56a5517fb830c7f8d7be5f9c98b9cd45a45fd7eb#diff-11

**Comment by djmitche** [comment]
Amanda doesn't do a very good job of maintaining API compatibility right now.  It'd be better to get this into the Amanda source tree, and maintained there, rather than try to target multiple versions.  That said, any noise you make about API compatibility can only help Amanda.

**Comment by marxarelli** [comment]
A fix for this has long since been committed along with many other great enhancements by [Jan](https://github.com/janekr/amlvm-snapshot).
